---
- name: Request agent to rollback snapshot
  uri:
    url: "http://{{ inventory_hostname }}:8080/snapshot/rollback"
    method: POST
    body: "{\"name\": \"{{ snapshot_name }}\"}"
    body_format: json
    status_code: 200
  register: rollback_res

- name: Show rollback response
  debug:
    var: rollback_res.json
